events {}

http {
    # 사용자가 정하는 이름(Host)에는 하이픈(-)을 씁니다. (Tomcat 호환성)
    upstream spring-cluster {
        server spring-app:8080;
    }

    server {
        listen 80;

        location / {
            # Nginx 명령어(directive)는 언더바(_)를 유지해야 합니다.
            proxy_pass http://spring-cluster;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}